#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Orgine.Android.Resource", IsApplication=true)]

namespace Orgine.Android
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xenko.Resource.Id.EditTextLayout = global::Orgine.Android.Resource.Id.EditTextLayout;
			global::Xenko.Resource.Id.GameMainLayout = global::Orgine.Android.Resource.Id.GameMainLayout;
			global::Xenko.Resource.Id.GameViewLayout = global::Orgine.Android.Resource.Id.GameViewLayout;
			global::Xenko.Resource.Layout.Game = global::Orgine.Android.Resource.Layout.Game;
			global::Xenko.Navigation.Resource.Id.EditTextLayout = global::Orgine.Android.Resource.Id.EditTextLayout;
			global::Xenko.Navigation.Resource.Id.GameMainLayout = global::Orgine.Android.Resource.Id.GameMainLayout;
			global::Xenko.Navigation.Resource.Id.GameViewLayout = global::Orgine.Android.Resource.Id.GameViewLayout;
			global::Xenko.Navigation.Resource.Layout.Game = global::Orgine.Android.Resource.Layout.Game;
			global::Xenko.Physics.Resource.Id.EditTextLayout = global::Orgine.Android.Resource.Id.EditTextLayout;
			global::Xenko.Physics.Resource.Id.GameMainLayout = global::Orgine.Android.Resource.Id.GameMainLayout;
			global::Xenko.Physics.Resource.Id.GameViewLayout = global::Orgine.Android.Resource.Id.GameViewLayout;
			global::Xenko.Physics.Resource.Layout.Game = global::Orgine.Android.Resource.Layout.Game;
			global::Xenko.UI.Resource.Id.EditTextLayout = global::Orgine.Android.Resource.Id.EditTextLayout;
			global::Xenko.UI.Resource.Id.GameMainLayout = global::Orgine.Android.Resource.Id.GameMainLayout;
			global::Xenko.UI.Resource.Id.GameViewLayout = global::Orgine.Android.Resource.Id.GameViewLayout;
			global::Xenko.UI.Resource.Layout.Game = global::Orgine.Android.Resource.Layout.Game;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F010000
			public const int Icon = 2130771968;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F020000
			public const int EditTextLayout = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int GameMainLayout = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int GameViewLayout = 2130837506;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F030000
			public const int Game = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
	}
}
#pragma warning restore 1591
